allowBuilds:
    '@parcel/watcher': true
    '@swc/core': true
    esbuild: true
    protobufjs: true
    sharp: true
    unrs-resolver: true
    '@firebase/util': true

minimumReleaseAge: 10080 # 60 * 24 * 7 for a week

minimumReleaseAgeExclude:
    - '@y9san9/panzoom@9.4.4-fix1 || 9.4.4-fix2'
